# What's the version of NumPy that you installed?

In [1]:
import numpy as np
np.__version__

'1.19.5'

# What's the version of Pandas?

In [3]:
import pandas as pd
pd.__version__

'1.3.4'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-11-02 08:14:07--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  1.47MB/s    in 1.0s    

2021-11-02 08:14:08 (1.47 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [5]:
!ls

README.md         data.csv          homework_01.ipynb


In [6]:
df = pd.read_csv('data.csv')

In [7]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# What's the average price of BMW cars in the dataset?

In [16]:
df[df['Make'] == 'BMW']['MSRP'].mean()

61546.76347305389

#   Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). 

In [19]:
subset = df[df['Year'] >= 2015].head()

In [20]:
subset.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

# How many of them have missing values for Engine HP?

In [27]:
df['Engine HP'].isnull().sum()

69

- Calculate the average "Engine HP" in the dataset.
- Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
- Now, calcualte the average of "Engine HP" again.
- Has it changed?

In [29]:
hp_engine_mean = round(df['Engine HP'].mean())

In [30]:
hp_engine_mean

249

In [33]:
df['Engine HP'] = df['Engine HP'].fillna(hp_engine_mean)

In [34]:
df['Engine HP'].isnull().sum()

0

In [35]:
round(df['Engine HP'].mean())

249

- Select all the "Rolls-Royce" cars from the dataset.
- Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
- Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- What's the sum of all the elements of the result?

In [39]:
rolls_royce = df[df['Make'] == 'Rolls-Royce']

In [40]:
rolls_royce.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [42]:
rolls_royce = rolls_royce[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [43]:
rolls_royce.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [45]:
rolls_royce = rolls_royce.drop_duplicates()

In [46]:
rolls_royce.count()

Engine HP           7
Engine Cylinders    7
highway MPG         7
dtype: int64

In [47]:
X = rolls_royce.values

In [48]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [49]:
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [65]:
XTX = np.dot(X.T, X)

In [66]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [71]:
XTX_inv = np.linalg.inv(XTX)

In [72]:
XTX_inv.round(2)

array([[ 0.  ,  0.  , -0.  ],
       [ 0.  ,  0.11, -0.09],
       [-0.  , -0.09,  0.11]])

In [73]:
XTX_inv.sum()

0.032212320677486125

- Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the value of the first element of w?.

In [76]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [77]:
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [83]:
w = np.dot(XTX_inv, X.T) * y

In [85]:
w[0]

array([-4.86592076,  3.70158161, -0.44514862,  1.72227877, -1.39491731,
       -1.98126399,  3.46328627])